name: PHP Unit Test

on:
  push:
    branches: [ "b-6.1.x" ]
  pull_request:
    branches: [ "b-6.1.x" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Setup IDE helper
        run: php ./ide-helper.php

      - name: Unit tests
        run: php ./vendor/bin/phpunit